import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Navbar from '../components/Navbar/Navbar'

const Home: NextPage = () => {
  return (
    <div className='lg:px-20 sm:px-4'>
      <Head>
        <title>Fitup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
    </div>
  )
}

export default Home
