import type { NextPage } from 'next'
import Head from 'next/head'
import FitYourBody from '../components/FitYourBody/FitYourBody'
import Hero from '../components/Hero/Hero'
import MiniAdvert from '../components/MiniAdvert/MiniAdvert'
import OurSolution from '../components/OurSolution/OurSolution'
import OurTrainers from '../components/OurTrainers/OurTrainers'
import PricingPlan from '../components/PricingPlan/PricingPlan'
import Testimonial from '../components/Testimonial/Testimonial'

const Home: NextPage = () => {
  return (
    <div className='lg:px-20 sm:px-4'>
      <Head>
        <title>Fitup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <MiniAdvert />
      <FitYourBody />
      <OurSolution />
      <PricingPlan />
      <OurTrainers />
      <Testimonial />

    </div>
  )
}

export default Home
